### ISSUE TITLE
Build failures due to missing Numpy

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2737]
GitHub Actions on Mac and Windows fail due to missing Numpy, also reported by other users (@jimmyDunne) need to make the process of finding numpy and populating PYTHON_NUMPY_INCLUDE_DIR more robust.

**Comment by moorepants** [comment]
CMake can find NumPy: https://cmake.org/cmake/help/v3.17/module/FindPython.html

NumPy also has this function: https://numpy.org/devdocs/reference/generated/numpy.get_include.html which is generally helpful.

**Comment by chrisdembia** [comment]
@aymanhab I see you are working on this directly on master, which is not great but I understand given the fact that the GitHub Actions are run only on master.

It would be great to fix this in the same way we do for Moco, which successfully uses GitHub Actions and NumPy.

https://github.com/opensim-org/opensim-moco/blob/82a13eb2c3fb6ce9aa88547f4e1895e467409c23/.github/workflows/continuous_integration.yml#L30-L31

https://github.com/opensim-org/opensim-moco/blob/82a13eb2c3fb6ce9aa88547f4e1895e467409c23/.github/workflows/continuous_integration.yml#L156-L161

@moorepants that new updated FindPython in CMake is neat! It seems like that update occurred in [CMake 3.14](https://cmake.org/cmake/help/v3.14/module/FindPython.html); when we update our minimum CMake dependency we should leverage this. 

We are using `numpy.get_include()` in `FindNumPy.cmake`: https://github.com/opensim-org/opensim-core/blob/master/cmake/FindNumPy.cmake

**Comment by aymanhab** [comment]
@chrisdembia yes unfortunately it has to be done on master . Thanks for the pointer.

**Comment by aymanhab** [comment]
I updated the files for github actions and they're building now (past numpy issue), however will leave this issue open since we don't know how common was @jimmyDunne scenario, maybe fixed by upgrading Cmake as suggested by @moorepants

**Comment by RobertCalise** [comment]
I'm getting what I think is a similar error. MacOS 10.15.4, cmake 3.17.1 installed by Homebrew. Following the process described in the README. I can successfully build on Ubuntu 18.04, but not my Mac.

```
Scanning dependencies of target _simulation
[ 91%] Building CXX object Bindings/Python/CMakeFiles/_simulation.dir/python_simulation_wrap.cxx.o
[ 92%] Linking CXX shared library ../../_simulation.so
Copying _simulation library to python package in build directory.
[ 92%] Built target _simulation
[ 93%] Linking CXX shared library ../../../libosimJavaJNI.dylib
[ 93%] Built target osimJavaJNI
make: *** [all] Error 2
```

I ran `make --debug=j` to see if it would shed some light on what's going on, and the output I get is: 

```
[ 90%] Building CXX object Bindings/Python/CMakeFiles/_simbody.dir/python_simbody_wrap.cxx.o
Reaping winning child 0x7ff23840c0c0 PID 49247
Live child 0x7ff23840c0c0 (Bindings/Python/CMakeFiles/_simbody.dir/python_simbody_wrap.cxx.o) PID 49248
/Users/rcalise/opensim/opensim_build/Bindings/Python/python_simbody_wrap.cxx:3510:10: fatal error: 'numpy/arrayobject.h'
      file not found
#include <numpy/arrayobject.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
Reaping losing child 0x7ff23840c0c0 PID 49248
make[2]: *** [Bindings/Python/CMakeFiles/_simbody.dir/python_simbody_wrap.cxx.o] Error 1
Removing child 0x7ff23840c0c0 PID 49248 from chain.
Reaping losing child 0x7ffb6670b7d0 PID 49246
make[1]: *** [Bindings/Python/CMakeFiles/_simbody.dir/all] Error 2
Removing child 0x7ffb6670b7d0 PID 49246 from chain.
Reaping losing child 0x7fa43a40d950 PID 49150
make: *** [all] Error 2
Removing child 0x7fa43a40d950 PID 49150 from chain.
```

So even though PYTHON_NUMPY_INCLUDE_DIR is set in ~/.zshrc, it's still not finding numpy, even though it's definitely installed, and ostensibly set to look in the right place:

```
➜  opensim_build python --version
Python 3.7.7

➜  opensim_build pip install numpy
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (1.18.2)

➜  opensim_build echo $PYTHON_NUMPY_INCLUDE_DIR
/usr/local/lib/python3.7/site-packages/numpy/core/include
```

**Comment by chrisdembia** [comment]
@RobertCalise `PYTHON_NUMPY_INCLUDE_DIR` is a CMake variable that should be set for you automatically; can you show the output of `cmake . -LAH` from your `opensim-core` build folder?

I think setting `PYTHON_NUMPY_INCLUDE_DIR` as an environment variable will have no effect.

It may be easier to resolve this over a quick phone call; you can contact me via my email address on my GitHub profile.

**Comment by RobertCalise** [comment]
@chrisdembia will email you shortly.

PYTHON_NUMPY_INCLUDE_DIR is nowhere to be found in that output, shown here:
https://gist.github.com/RobertCalise/b7c562c99821fcf922d91916dcfd891a

**Comment by chrisdembia** [comment]
@RobertCalise resolved the issue by clearing the CMake cache and getting rid of pyenv.

**Comment by chrisdembia** [comment]
@aymanhab is this resolved?

**Comment by aymanhab** [comment]
Yes, seems to be working and github Actions work, will close
