### ISSUE TITLE
prescribeControlForActuator is not recognized in python

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#1241]
Hi, I've been working with the opensim software in windows but now I'm moving to the API, specifically transferring to python. I'm trying to run the example moving the code of elbow arm algorithm to python, as it is shown below:

```
import opensim

model = opensim.Model()
model.setUseVisualizer(True)
humerus = opensim.Body("humerus",1, opensim.Vec3(0), opensim.Inertia(0))
radius = opensim.Body("radius",1, opensim.Vec3(0), opensim.Inertia(0))
shoulder = opensim.PinJoint("shoulder", model.getGround(), opensim.Vec3(0), opensim.Vec3(0), humerus, opensim.Vec3(0,1,0), opensim.Vec3(0))
elbow = opensim.PinJoint("elbow", humerus, opensim.Vec3(0), opensim.Vec3(0), radius, opensim.Vec3(0,1,0),opensim.Vec3(0))

#Add a muscle that flexes the elbow
biceps = opensim.Millard2012EquilibriumMuscle("biceps", 200, 0.6, 0.55, 0)
biceps.addNewPathPoint("origin", humerus, opensim.Vec3(0,0.8,0))
biceps.addNewPathPoint("insertion", radius, opensim.Vec3(0,0.7,0))
print(type(biceps))

# Add a controller that specifies the excitation of the muscle.
#opensim.Controller.addActuator(1,biceps)
brain = opensim.PrescribedController().addActuator(biceps).prescribeControlForActuator("biceps", opensim.StepFunction(0.5, 3, 0.3, 1))

# Muscle excitation is 0.3 for the first 0.5 seconds, then increases to 1.
model.addBody(humerus)
model.addBody(radius)
model.addJoint(shoulder)
model.addJoint(elbow)
model.addForce(biceps)
#model.addController(brain)

# Add a console reporter to print the muscle fiber force and elbow angle.
reporter = opensim.ConsoleReporter().set_report_time_interval(1.0)
#reporter.updInput("inputs").connect(biceps.getOutput("fiber_force"))
#reporter.updInput("inputs").connect(
#    elbow.getCoordinateSet()[0].getOutput("value"), "elbow_angle")
#model.addComponent(reporter)

```
Unfortunately,  the library did not recognize the  prescribeControlForActuator class, showing the following error: 
```
brain = Opensim.PrescribedController().addActuator(biceps).prescribeControlForActuator("biceps", opensim.StepFunction(0.5, 3, 0.3, 1))
AttributeError: 'NoneType' object has no attribute 'prescribeControlForActuator'

```
I'm working on linux with the 4.0 version built and the python test passed successfully.
PD: I also found other classes that are not able to be read by python, but I think that It could be an error of programming.

I hope you can help me!

# Thanks a lot!

**Comment by chrisdembia** [comment]
Welcome to the API.

This example is already available in python, thanks to @wagglefoot. You can find it at `Bindings/Python/examples/build_simple_arm_model.py`.

`prescribeControlForActuator` is not a class. Also, this line of code is incorrect:
`#opensim.Controller.addActuator(1,biceps)`

You must first create an instance of a class before you can call methods on it (unless they are static methods):

```py
controller = opensim.PrescribedController()
controller.addActuator(...)
controller.prescribeControlForActuator(...)
```

You cannot chain these method calls as you were showing.

I'm going to close this issue because it is not a bug in the code. Please feel free to open the issue if you are more sure that there is a bug. In general, we try to use GitHub Issues only for known bugs (or desired features, etc.), not for discussion or user help. Usually, people should use the OpenSim forums for help.

**Comment by nikorose87** [comment]
It works great! Thank you...
